language: node_js
node_js:
  - '14.15'
install:
  - npm i
script:
  - npm run migrate
  - npm run test:nyc
after_success:
  - npm run cov:report
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'create database imigani_api_test;' -U postgres
